apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking
  namespace: mlflow-tracking
  labels:
    app: mlflow-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-tracking
  template:
    metadata:
      labels:
        app: mlflow-tracking
    spec:
      containers:
      - name: mlflow-tracking
        image: ghcr.io/crate/mlflow-cratedb:latest
        # command to do pip install boto3 and then start the mlflow server
        command: ["/bin/sh", "-c"]
        args:
        - |
          pip install boto3 &&
          mlflow-cratedb server \
            --backend-store-uri=crate://crate@cratedb.cratedb.svc.cluster.local:4200/?schema=mlflow \
            --artifacts-destination=s3://mlartifacts \
            --serve-artifacts \
            --host=0.0.0.0 \
            --gunicorn-opts=--log-level=debug    
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "500Mi"
            cpu: "0.50"
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://seaweedfs-s3.seaweedfs.svc.cluster.local:8333
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-secret-deployment
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret-deployment
              key: AWS_SECRET_ACCESS_KEY
